Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2023-12, with the labels that each got.

#25 Update MerlinAU.sh
  MerlinAU.sh
  README.md
  ToDoList.txt
  version.txt
Labels: bug, enhancement

#26 Update MerlinAU.sh
  MerlinAU.sh
Labels: bug, enhancement

#27 Dev v0.2.28 Targeted to Be New Master Release
  MerlinAU.sh
  README.md
  version.txt
Labels: enhancement

#31 Update MerlinAU.sh (Better memory management)
  MerlinAU.sh
  README.md
Labels: enhancement

#34 Update MerlinAU.sh with Memory Warnings
  MerlinAU.sh
  README.md
Labels: enhancement

#36 Update the Login Process and the Script Update Process for MerlinAU.sh
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#45 Quick Patch for improved safety
  MerlinAU.sh
  README.md
  version.txt
Labels: enhancement

#48 Update MerlinAU.sh Logging Solution to Stop Duplicating Mount Points
  MerlinAU.sh
Labels: bug

#52 Update MerlinAU.sh
  MerlinAU.sh
Labels: documentation, help wanted, question

#53 Update MerlinAU.sh ROG Logic
  MerlinAU.sh
Labels: enhancement

#54 Dev 0.2.40 Targeted as latest master/stable release
  MerlinAU.sh
  version.txt
Labels: enhancement

#56 Extreme firetop cron/memory patch
  MerlinAU.sh
Labels: bug

#57 URGENT BUG FIX - Dev 0.2.42 Targeted as Next Stable/Master Release
  MerlinAU.sh
  version.txt
Labels: bug

#61 Dev to Main Target 0.2.43
  MerlinAU.sh
  version.txt
Labels: enhancement
