Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-10, with the labels that each got.

#305 Update Minimum Version
  MerlinAU.sh
Labels: dependencies

#306 Dev 1.3.1 as Next Stable Release
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, documentation, enhancement, dependencies

#311 Code Improvements
  MerlinAU.sh
Labels: enhancement

#313 Dev 1.3.2 as Next Stable Release
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
Labels: enhancement

#315 Testing Workflow 1.3.2
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
Labels: bug, enhancement

#333 Rolling back Workflow to Manual Branch Modifications
  .github/workflows/Create-NewReleases.yml
Labels: bug

#344 Update version.txt
  version.txt
Labels: good first issue
