Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-05, with the labels that each got.

#201 Node_MinorLogicFix
  MerlinAU.sh
Labels: bug

#204 Include New Logs Menu
  MerlinAU.sh
Labels: enhancement

#206 New menu option to view F/W Update log files.
  MerlinAU.sh
Labels: enhancement

#205 Better_Cron_Estimates
  MerlinAU.sh
Labels: enhancement

#208 Fix Future Estimates
  MerlinAU.sh
Labels: bug, enhancement

#209 Fixes, code cleanup & improvements
  MerlinAU.sh
Labels: bug

#211 Dev 1.1.3 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#214 Update GUI Menu Sizes, Fix Changelog Check (again), and Email Highlight Changelog Changes, SHA256 changes
  MerlinAU.sh
Labels: enhancement

#215 Minor code fixes & improvements.
  MerlinAU.sh
Labels: enhancement

#220 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#222 Fixed bug not filtering "Yes" responses properly.
  MerlinAU.sh
Labels: bug

#223 Minor Improvements
  MerlinAU.sh
Labels: enhancement
