Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-11, with the labels that each got.

#358 Dev 1.3.5 as Next Stable Release
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#367 Fixes: Cron Schedule Calculations, Changelog Verification, Post-Update Version Comparison
  MerlinAU.sh
Labels: bug, enhancement

#368 Improvements & Fixes
  MerlinAU.sh
Labels: bug

#369 Dev 1.3.7 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement, new feature
