Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-03, with the labels that each got.

#152 Allow Test of Login Credentials
  MerlinAU.sh
Labels: enhancement

#153 Enhancements for Login Password input.
  MerlinAU.sh
Labels: enhancement

#154 Include Password Tab Debounce
  MerlinAU.sh
Labels: enhancement

#155 Dev 1.0.6 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#156 Updating workflow to handle MAJOR.MINOR and Release Notes
  .github/workflows/Create-NewReleases.yml
Labels: enhancement

#160 Dev 1.0.7 as next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug

#163 Improved Memory Management
  MerlinAU.sh
Labels: enhancement

#165 Dev 1.0.8 Targeted as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#169 More Improvements for F/W Update Notification
  MerlinAU.sh
Labels: enhancement

#167 Update Memory Management
  MerlinAU.sh
Labels: enhancement

#173 Move Cron Option to Main Menu
  MerlinAU.sh
Labels: enhancement

#174 Dev 1.0.9 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#177 Update Git Release Flow
  .github/workflows/Create-NewReleases.yml
Labels: enhancement

#181 Dev 1.0.10 as Next Stable Release
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
  README.md
  version.txt
Labels: bug
