Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-06, with the labels that each got.

#227 Dev 1.2.0 As Next Stable Release
  MerlinAU.sh
  version.txt
Labels: bug, enhancement

#230 Changes to support "3006.102.X" ROG Patch
  MerlinAU.sh
Labels: enhancement

#234 Dev 1.2.1 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#236 Fix/Patch Cron Estimates
  MerlinAU.sh
Labels: bug

#238 Dev 1.2.2 as next stable release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug

#240 Code improvements when stopping services.
  MerlinAU.sh
Labels: bug, enhancement

#242 Fix Changelog Check Behavior
  MerlinAU.sh
Labels: bug

#243 Dev 1.2.3 as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#249 Small Improvements
  MerlinAU.sh
Labels: enhancement

#251 Dev 1.2.4 As Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement
