Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-01, with the labels that each got.

#62 Update MerlinAU.sh Cron Menu to Prompt User
  MerlinAU.sh
  version.txt
Labels: enhancement

#64 Update MerlinAU.sh Allowing Unsupported Users To Uninstall Completely
  MerlinAU.sh
  version.txt
Labels: enhancement

#68 Update MerlinAU.sh ROG Patch to Show ROG Options in Menu if Default Route is Taken Post-Setup
  MerlinAU.sh
Labels: bug

#69 Dev 02.49 Target as next Stable/Master Release To Fix ROG Behavior with Default Route
  MerlinAU.sh
  version.txt
Labels: bug

#70 Update MerlinAU.sh We Don't Allow E to Exit, remove from Menu
  MerlinAU.sh
  version.txt
Labels: bug

#72 Dev 0.2.51 Target as next Master/Stable Release.
  MerlinAU.sh
  version.txt
Labels: bug, enhancement

#74 Update MerlinAU.sh Fix the change_build_type Function to Exit without Changes
  MerlinAU.sh
Labels: bug

#75 Dev 0.2.52 as Next Stable/Master Release
  MerlinAU.sh
  version.txt
Labels: bug, enhancement

#77 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#80 Update MerlinAU.sh Settings
  MerlinAU.sh
Labels: enhancement

#81 Dev 0.2.53 Target as Next Master release
  MerlinAU.sh
  version.txt
Labels: enhancement

#82 Update MerlinAU.sh ROG Patch
  MerlinAU.sh
Labels: enhancement

#84 Update README.md
  README.md
Labels: documentation

#86 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#87 Update MerlinAU.sh for Change-Log Check
  MerlinAU.sh
Labels: enhancement

#92 Update MerlinAU.sh Intergrate backupmon if installed
  MerlinAU.sh
Labels: enhancement

#94 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#95 Update MerlinAU.sh Allow Upgrade from Beta to Release
  MerlinAU.sh
Labels: enhancement

#97 Update MerlinAU.sh
  MerlinAU.sh
Labels: bug

#96 Update MerlinAU.sh Update to V1.0
  MerlinAU.sh
Labels: bug, enhancement

#98 Dev 1.0.0 New Master Release - FIRST OFFICIAL RELEASE
  MerlinAU.sh
  version.txt
Labels: bug, documentation, enhancement

#107 Update MerlinAU.sh Updated the Changelog Review Logic
  MerlinAU.sh
Labels: enhancement

#108 Update MerlinAU.sh Changelog Fix to the Regex
  MerlinAU.sh
Labels: bug

#110 Update MerlinAU.sh Unmount
  MerlinAU.sh
Labels: bug, enhancement
