Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2024-02, with the labels that each got.

#113 Update MerlinAU.sh Cleanup
  MerlinAU.sh
Labels: bug

#114 Dev 1.0.2 Next Stable Release
  MerlinAU.sh
  version.txt
Labels: bug, enhancement

#117 Dev 1.0.3 Target as Next Stable Release
  MerlinAU.sh
  README.md
  version.txt
Labels: enhancement

#119 Update MerlinAU.sh Translate All Crons into Human Readable Format
  MerlinAU.sh
Labels: enhancement

#123 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#125 Update MerlinAU.sh Backupmon Versioning Update
  MerlinAU.sh
Labels: bug, enhancement

#127 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#128 Update MerlinAU.sh Quick Patch for ROG Menu
  MerlinAU.sh
Labels: enhancement

#129 Updated MerlinAU.sh
  MerlinAU.sh
Labels: documentation

#130 Dev 1.0.4 Targeted as Next Major Release
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, documentation, enhancement

#132 Update MerlinAU.sh-Redirect-Unzip-Output
  MerlinAU.sh
Labels: enhancement

#133 Update MerlinAU.sh Menu Patch
  MerlinAU.sh
Labels: enhancement

#136 Update MerlinAU.sh
  MerlinAU.sh
Labels: enhancement

#141 Dev 1.0.5 Targeted as Next Stable Release
  CONTRIBUTING.md
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement

#145 ROG Failure Email Patch
  MerlinAU.sh
Labels: bug

#151 Resolve Issues with HTTPS Only Config
  MerlinAU.sh
Labels: bug
