Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2025-03, with the labels that each got.

#378 Include MerlinAU Add-on WebUI
  MerlinAU.asp
  MerlinAU.sh
  README.md
  version.txt
Labels: enhancement

#418 Fix The Update Check Status Post Upgrade
  MerlinAU.sh
Labels: bug

#420 Allow viewing of the changelog from the WebUI
  MerlinAU.asp
  MerlinAU.sh
Labels: enhancement, new feature

#424 Typo Correction
  MerlinAU.sh
Labels: bug

#426 Improvements to support APs
  MerlinAU.sh
  README.md
Labels: enhancement

#430 Backport 1.4.0 Fixes to 1.3.11
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, enhancement
