Repository ExtremeFiretop/MerlinAutoUpdate-Router, pull requests merged in 2025-02, with the labels that each got.

#398 Fix ROG and TUG Build Type Selection from WebUI
  MerlinAU.asp
Labels: bug, enhancement

#399 Initialize a Default Build Type for ROG and TUF
  MerlinAU.asp
  MerlinAU.sh
Labels: enhancement

#401 More Build Type Refinements
  MerlinAU.sh
Labels: enhancement

#407 Resolve Checksums on GT-AX1000 Issue: 406
  MerlinAU.sh
Labels: bug

#410 Dev 1.3.10 as Next Stable Release
  .github/workflows/Create-NewReleases.yml
  MerlinAU.sh
  README.md
  version.txt
Labels: bug, documentation, enhancement, dependencies, new feature

#413 Fix WebUI Changelog Check Approval
  MerlinAU.asp
  MerlinAU.sh
Labels: bug, enhancement

#416 UI Improvements
  MerlinAU.asp
  MerlinAU.sh
Labels: enhancement
